"""exposure model

Revision ID: 29ad491ada0f
Revises: 8d95a05b5cb9
Create Date: 2023-04-24 11:11:59.222632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '29ad491ada0f'
down_revision = '8d95a05b5cb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutouts_created_at'), 'cutouts', ['created_at'], unique=False)
    op.create_index(op.f('ix_cutouts_id'), 'cutouts', ['id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_created_at'), 'measurements', ['created_at'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_table('source_lists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_lists_created_at'), 'source_lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_lists_id'), 'source_lists', ['id'], unique=False)
    op.create_table('world_coordinates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_coordinates_created_at'), 'world_coordinates', ['created_at'], unique=False)
    op.create_index(op.f('ix_world_coordinates_id'), 'world_coordinates', ['id'], unique=False)
    op.create_table('zero_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zero_points_created_at'), 'zero_points', ['created_at'], unique=False)
    op.create_index(op.f('ix_zero_points_id'), 'zero_points', ['id'], unique=False)
    op.add_column('exposures', sa.Column('header', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('exposures', sa.Column('filename', sa.Text(), nullable=False))
    op.add_column('exposures', sa.Column('mjd', sa.Double(), nullable=False))
    op.add_column('exposures', sa.Column('exp_time', sa.Float(), nullable=False))
    op.add_column('exposures', sa.Column('filter', sa.Text(), nullable=False))
    op.add_column('exposures', sa.Column('instrument', sa.Text(), nullable=False))
    op.add_column('exposures', sa.Column('telescope', sa.Text(), nullable=False))
    op.add_column('exposures', sa.Column('num_ccds', sa.Integer(), nullable=False))
    op.add_column('exposures', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('exposures', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('exposures', sa.Column('project', sa.Text(), nullable=False))
    op.add_column('exposures', sa.Column('target', sa.Text(), nullable=False))
    op.add_column('exposures', sa.Column('gallat', sa.Double(), nullable=True))
    op.add_column('exposures', sa.Column('gallon', sa.Double(), nullable=True))
    op.add_column('exposures', sa.Column('ecllat', sa.Double(), nullable=True))
    op.add_column('exposures', sa.Column('ecllon', sa.Double(), nullable=True))
    op.add_column('exposures', sa.Column('ra', sa.Double(), nullable=False))
    op.add_column('exposures', sa.Column('dec', sa.Double(), nullable=False))

    # ref: https://stackoverflow.com/a/23206636
    op.get_bind().execute(text('CREATE EXTENSION IF NOT EXISTS q3c;'))
    op.create_index('exposures_q3c_ang2ipix_idx', 'exposures', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_index(op.f('ix_exposures_ecllat'), 'exposures', ['ecllat'], unique=False)
    op.create_index(op.f('ix_exposures_exp_time'), 'exposures', ['exp_time'], unique=False)
    op.create_index(op.f('ix_exposures_filename'), 'exposures', ['filename'], unique=True)
    op.create_index(op.f('ix_exposures_filter'), 'exposures', ['filter'], unique=False)
    op.create_index(op.f('ix_exposures_gallat'), 'exposures', ['gallat'], unique=False)
    op.create_index(op.f('ix_exposures_instrument'), 'exposures', ['instrument'], unique=False)
    op.create_index(op.f('ix_exposures_mjd'), 'exposures', ['mjd'], unique=False)
    op.create_index(op.f('ix_exposures_project'), 'exposures', ['project'], unique=False)
    op.create_index(op.f('ix_exposures_target'), 'exposures', ['target'], unique=False)
    op.create_index(op.f('ix_exposures_telescope'), 'exposures', ['telescope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exposures_telescope'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_target'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_project'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_mjd'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_instrument'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_gallat'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_filter'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_filename'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_exp_time'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_ecllat'), table_name='exposures')
    op.drop_index('exposures_q3c_ang2ipix_idx', table_name='exposures')
    op.drop_column('exposures', 'dec')
    op.drop_column('exposures', 'ra')
    op.drop_column('exposures', 'ecllon')
    op.drop_column('exposures', 'ecllat')
    op.drop_column('exposures', 'gallon')
    op.drop_column('exposures', 'gallat')
    op.drop_column('exposures', 'target')
    op.drop_column('exposures', 'project')
    op.drop_column('exposures', 'height')
    op.drop_column('exposures', 'width')
    op.drop_column('exposures', 'num_ccds')
    op.drop_column('exposures', 'telescope')
    op.drop_column('exposures', 'instrument')
    op.drop_column('exposures', 'filter')
    op.drop_column('exposures', 'exp_time')
    op.drop_column('exposures', 'mjd')
    op.drop_column('exposures', 'filename')
    op.drop_column('exposures', 'header')
    op.drop_index(op.f('ix_zero_points_id'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points_created_at'), table_name='zero_points')
    op.drop_table('zero_points')
    op.drop_index(op.f('ix_world_coordinates_id'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_created_at'), table_name='world_coordinates')
    op.drop_table('world_coordinates')
    op.drop_index(op.f('ix_source_lists_id'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists_created_at'), table_name='source_lists')
    op.drop_table('source_lists')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_at'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_cutouts_id'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts_created_at'), table_name='cutouts')
    op.drop_table('cutouts')
    # ### end Alembic commands ###
