"""image references and columns

Revision ID: 2c2c4518c041
Revises: aae2097b2750
Create Date: 2023-11-23 13:41:07.480473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2c4518c041'
down_revision = 'aae2097b2750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('ref_entry_id', sa.BigInteger(), nullable=True))
    op.add_column('images', sa.Column('is_sub', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_coadd', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_warped', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('sky_sub_done', sa.BOOLEAN(), nullable=False))
    op.add_column('images', sa.Column('fwhm_estimate', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('zero_point_estimate', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('lim_mag_estimate', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('bkg_mean_estimate', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('bkg_rms_estimate', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('_upstream_bitflag', sa.BIGINT(), nullable=False))
    op.create_index(op.f('ix_images__upstream_bitflag'), 'images', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_images_bkg_mean_estimate'), 'images', ['bkg_mean_estimate'], unique=False)
    op.create_index(op.f('ix_images_bkg_rms_estimate'), 'images', ['bkg_rms_estimate'], unique=False)
    op.create_index(op.f('ix_images_fwhm_estimate'), 'images', ['fwhm_estimate'], unique=False)
    op.create_index(op.f('ix_images_is_coadd'), 'images', ['is_coadd'], unique=False)
    op.create_index(op.f('ix_images_is_sub'), 'images', ['is_sub'], unique=False)
    op.create_index(op.f('ix_images_is_warped'), 'images', ['is_warped'], unique=False)
    op.create_index(op.f('ix_images_lim_mag_estimate'), 'images', ['lim_mag_estimate'], unique=False)
    op.create_index(op.f('ix_images_ref_entry_id'), 'images', ['ref_entry_id'], unique=False)
    op.create_index(op.f('ix_images_zero_point_estimate'), 'images', ['zero_point_estimate'], unique=False)
    op.drop_constraint('images_new_image_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_ref_image_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key('images_ref_entry_id_fkey', 'images', 'reference_images', ['ref_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_column('images', 'ref_image_id')
    op.drop_column('images', 'new_image_id')
    op.add_column('psfs', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('psfs', sa.Column('_upstream_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('psfs', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_psfs__bitflag'), 'psfs', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_psfs__upstream_bitflag'), 'psfs', ['_upstream_bitflag'], unique=False)
    op.add_column('reference_images', sa.Column('source_list_id', sa.BigInteger(), nullable=True))
    op.add_column('reference_images', sa.Column('psf_id', sa.BigInteger(), nullable=True))
    op.add_column('reference_images', sa.Column('wcs_id', sa.BigInteger(), nullable=True))
    op.add_column('reference_images', sa.Column('zp_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_reference_images_psf_id'), 'reference_images', ['psf_id'], unique=False)
    op.create_index(op.f('ix_reference_images_source_list_id'), 'reference_images', ['source_list_id'], unique=False)
    op.create_index(op.f('ix_reference_images_wcs_id'), 'reference_images', ['wcs_id'], unique=False)
    op.create_index(op.f('ix_reference_images_zp_id'), 'reference_images', ['zp_id'], unique=False)
    op.create_foreign_key('reference_images_zp_id_fkey', 'reference_images', 'zero_points', ['zp_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reference_images_psf_id_fkey', 'reference_images', 'psfs', ['psf_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reference_images_source_list_id_fkey', 'reference_images', 'source_lists', ['source_list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reference_images_wcs_id_fkey', 'reference_images', 'world_coordinates', ['wcs_id'], ['id'], ondelete='CASCADE')
    op.add_column('source_lists', sa.Column('_upstream_bitflag', sa.BIGINT(), nullable=False))
    op.create_index(op.f('ix_source_lists__upstream_bitflag'), 'source_lists', ['_upstream_bitflag'], unique=False)
    op.add_column('world_coordinates', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('world_coordinates', sa.Column('_upstream_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('world_coordinates', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_world_coordinates__bitflag'), 'world_coordinates', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_world_coordinates__upstream_bitflag'), 'world_coordinates', ['_upstream_bitflag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_coordinates__upstream_bitflag'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates__bitflag'), table_name='world_coordinates')
    op.drop_column('world_coordinates', 'description')
    op.drop_column('world_coordinates', '_upstream_bitflag')
    op.drop_column('world_coordinates', '_bitflag')
    op.drop_index(op.f('ix_source_lists__upstream_bitflag'), table_name='source_lists')
    op.drop_column('source_lists', '_upstream_bitflag')
    op.drop_constraint('reference_images_wcs_id_fkey', 'reference_images', type_='foreignkey')
    op.drop_constraint('reference_images_source_list_id_fkey', 'reference_images', type_='foreignkey')
    op.drop_constraint('reference_images_psf_id_fkey', 'reference_images', type_='foreignkey')
    op.drop_constraint('reference_images_zp_id_fkey', 'reference_images', type_='foreignkey')
    op.drop_index(op.f('ix_reference_images_zp_id'), table_name='reference_images')
    op.drop_index(op.f('ix_reference_images_wcs_id'), table_name='reference_images')
    op.drop_index(op.f('ix_reference_images_source_list_id'), table_name='reference_images')
    op.drop_index(op.f('ix_reference_images_psf_id'), table_name='reference_images')
    op.drop_column('reference_images', 'zp_id')
    op.drop_column('reference_images', 'wcs_id')
    op.drop_column('reference_images', 'psf_id')
    op.drop_column('reference_images', 'source_list_id')
    op.drop_index(op.f('ix_psfs__upstream_bitflag'), table_name='psfs')
    op.drop_index(op.f('ix_psfs__bitflag'), table_name='psfs')
    op.drop_column('psfs', 'description')
    op.drop_column('psfs', '_upstream_bitflag')
    op.drop_column('psfs', '_bitflag')
    op.add_column('images', sa.Column('new_image_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('ref_image_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('images_ref_entry_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key('images_ref_image_id_fkey', 'images', 'images', ['ref_image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('images_new_image_id_fkey', 'images', 'images', ['new_image_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_images_zero_point_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_ref_entry_id'), table_name='images')
    op.drop_index(op.f('ix_images_lim_mag_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_is_warped'), table_name='images')
    op.drop_index(op.f('ix_images_is_sub'), table_name='images')
    op.drop_index(op.f('ix_images_is_coadd'), table_name='images')
    op.drop_index(op.f('ix_images_fwhm_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_bkg_rms_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_bkg_mean_estimate'), table_name='images')
    op.drop_index(op.f('ix_images__upstream_bitflag'), table_name='images')
    op.create_index('ix_images_ref_image_id', 'images', ['ref_image_id'], unique=False)
    op.create_index('ix_images_new_image_id', 'images', ['new_image_id'], unique=False)
    op.drop_column('images', '_upstream_bitflag')
    op.drop_column('images', 'bkg_rms_estimate')
    op.drop_column('images', 'bkg_mean_estimate')
    op.drop_column('images', 'lim_mag_estimate')
    op.drop_column('images', 'zero_point_estimate')
    op.drop_column('images', 'fwhm_estimate')
    op.drop_column('images', 'sky_sub_done')
    op.drop_column('images', 'is_warped')
    op.drop_column('images', 'is_coadd')
    op.drop_column('images', 'is_sub')
    op.drop_column('images', 'ref_entry_id')
    # ### end Alembic commands ###
