"""object objects

Revision ID: 5acdc145edcd
Revises: b2129499bfcd
Create Date: 2024-04-02 14:42:34.432726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5acdc145edcd'
down_revision = 'b2129499bfcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discovery_ra', sa.Float(), nullable=False),
    sa.Column('discovery_dec', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_created_at'), 'objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_objects_discovery_dec'), 'objects', ['discovery_dec'], unique=False)
    op.create_index(op.f('ix_objects_discovery_ra'), 'objects', ['discovery_ra'], unique=False)
    op.create_index(op.f('ix_objects_ecllat'), 'objects', ['ecllat'], unique=False)
    op.create_index(op.f('ix_objects_gallat'), 'objects', ['gallat'], unique=False)
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_index(op.f('ix_objects_name'), 'objects', ['name'], unique=False)
    op.create_index('objects_discovery_q3c_ang2ipix_idx', 'objects', [sa.text('q3c_ang2ipix(discovery_ra, discovery_dec)')], unique=False)
    op.create_index('objects_q3c_ang2ipix_idx', 'objects', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_table('measurements_object_association',
    sa.Column('measurements_id', sa.Integer(), nullable=False),
    sa.Column('objects_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measurements_id'], ['measurements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objects_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('measurements_id', 'objects_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements_object_association')
    op.drop_index('objects_q3c_ang2ipix_idx', table_name='objects')
    op.drop_index('objects_discovery_q3c_ang2ipix_idx', table_name='objects')
    op.drop_index(op.f('ix_objects_name'), table_name='objects')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_gallat'), table_name='objects')
    op.drop_index(op.f('ix_objects_ecllat'), table_name='objects')
    op.drop_index(op.f('ix_objects_discovery_ra'), table_name='objects')
    op.drop_index(op.f('ix_objects_discovery_dec'), table_name='objects')
    op.drop_index(op.f('ix_objects_created_at'), table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###
